build_from:
  aarch64: ghcr.io/home-assistant/aarch64-addon-debian-base:12.2.0
  amd64: ghcr.io/home-assistant/amd64-addon-debian-base:12.2.0
  armv7: ghcr.io/home-assistant/armv7-addon-debian-base:12.2.0
args: {}
